apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-nodejs
  namespace: auth-service-nodejs
  labels:
    app: auth-service-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-nodejs
  template:
    metadata:
      labels:
        app: auth-service-nodejs
    spec:
      containers:
        - name: auth-service-nodejs
          image: image-registry.openshift-image-registry.svc:5000/auth-service-nodejs/auth-service-nodejs:latest
          ports:
            - containerPort: 8085
              name: http
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8085"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-service-db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-service-db-secret
                  key: DB_PORT
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: auth-service-db-secret
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-db-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secret
                  key: JWT_SECRET
            - name: FRONTEND_URL
              value: "https://vite-metronic-9-auth-service-nodejs.apps.rosa.tg-sandbox.aibk.p3.openshiftapps.com"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - ALL 