apiVersion: v1
kind: Secret
metadata:
  name: auth-service-db-secret
  namespace: auth-service-nodejs
type: Opaque
data:
  DB_HOST: MTg4LjE2Ni4yNTQuMTIx  # 188.166.254.121
  DB_PORT: NjU0Mw==               # 6543
  DB_DATABASE: ZGVtb19kYg==       # demo_db
  DB_USERNAME: cG9zdGdyZXM=       # postgres
  DB_PASSWORD: cG9zdGdyZXM=       # postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: auth-service-nodejs
type: Opaque
data:
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXk=  # super_secret_jwt_key 